// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiCxZEkEjGoTLNngFz4XimqCk34i43grQ',
    appId: '1:1025432711667:web:1a7ab1bce9549782b7e286',
    messagingSenderId: '1025432711667',
    projectId: 'eva2-c65e2',
    authDomain: 'eva2-c65e2.firebaseapp.com',
    databaseURL: 'https://eva2-c65e2-default-rtdb.firebaseio.com',
    storageBucket: 'eva2-c65e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-dhGxVozMcxAuJ1FcYhYAHHZY3cs3o1w',
    appId: '1:1025432711667:android:119a05bce0978495b7e286',
    messagingSenderId: '1025432711667',
    projectId: 'eva2-c65e2',
    databaseURL: 'https://eva2-c65e2-default-rtdb.firebaseio.com',
    storageBucket: 'eva2-c65e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAseDU7NmnbFrL5oNKm6vmC5pfcH5AJ3Tg',
    appId: '1:1025432711667:ios:575c5259dadcd804b7e286',
    messagingSenderId: '1025432711667',
    projectId: 'eva2-c65e2',
    databaseURL: 'https://eva2-c65e2-default-rtdb.firebaseio.com',
    storageBucket: 'eva2-c65e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAseDU7NmnbFrL5oNKm6vmC5pfcH5AJ3Tg',
    appId: '1:1025432711667:ios:575c5259dadcd804b7e286',
    messagingSenderId: '1025432711667',
    projectId: 'eva2-c65e2',
    databaseURL: 'https://eva2-c65e2-default-rtdb.firebaseio.com',
    storageBucket: 'eva2-c65e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiCxZEkEjGoTLNngFz4XimqCk34i43grQ',
    appId: '1:1025432711667:web:2a4430dc940a8999b7e286',
    messagingSenderId: '1025432711667',
    projectId: 'eva2-c65e2',
    authDomain: 'eva2-c65e2.firebaseapp.com',
    databaseURL: 'https://eva2-c65e2-default-rtdb.firebaseio.com',
    storageBucket: 'eva2-c65e2.firebasestorage.app',
  );
}
